/*
@TargetNode='WindowsVirtualDesktopAgents'
@GeneratedBy=fafriha
@GenerationDate=10/25/2020 03:02:18
@GenerationHost=DESKTOP-HPBLBTK
*/

instance of cChocoInstaller as $cChocoInstaller1ref
{
ModuleVersion = "2.4.1.0";
 ResourceID = "[cChocoInstaller]Choco::[Audit]./Config::[Audit]./Config";
 ModuleName = "cChoco";
 SourceInfo = "C:\\Users\\fafriha\\.Azure\\Repos\\azure-as-code\\windows-virtual-desktop\\current\\powershell\\configurations\\Audit-WVDAgents.ps1::7::9::cChocoInstaller";
 InstallDir = "c:\\choco";
 ConfigurationName = "Audit";
};
instance of cChocoPackageInstall as $cChocoPackageInstall1ref
{
SourceInfo = "C:\\Users\\fafriha\\.Azure\\Repos\\azure-as-code\\windows-virtual-desktop\\current\\powershell\\configurations\\Audit-WVDAgents.ps1::12::9::cChocoPackageInstaller";
 Name = "wvd-boot-loader";
 ModuleName = "cChoco";
 ResourceID = "[cChocoPackageInstaller]WVDAgentBootloader::[Audit]./Config::[Audit]./Config";
 Ensure = "Present";
 ModuleVersion = "2.4.1.0";

DependsOn = {
    "[cChocoInstaller]Choco::[Audit]./Config::[Audit]./Config"};
 ConfigurationName = "Audit";
};
instance of cChocoPackageInstall as $cChocoPackageInstall2ref
{
SourceInfo = "C:\\Users\\fafriha\\.Azure\\Repos\\azure-as-code\\windows-virtual-desktop\\current\\powershell\\configurations\\Audit-WVDAgents.ps1::19::9::cChocoPackageInstaller";
 Name = "wvd-agent";
 ModuleName = "cChoco";
 ResourceID = "[cChocoPackageInstaller]WVDAgent::[Audit]./Config::[Audit]./Config";
 Ensure = "Present";
 ModuleVersion = "2.4.1.0";

DependsOn = {
    "[cChocoInstaller]Choco::[Audit]./Config::[Audit]./Config"};
 ConfigurationName = "Audit";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="fafriha";

                        GenerationDate="10/25/2020 03:02:18";

                        GenerationHost="DESKTOP-HPBLBTK";

                        Name="Audit";

                    };
