## Subscribing to the event generated by the expiration of the registration token
resource "azurerm_eventgrid_event_subscription" "wvd" {
  name  = "es-azprd-frc-wvd-01"
  scope = azurerm_key_vault.wvd.id
  included_event_types = [
    "Microsoft.KeyVault.SecretExpired"
  ]

  azure_function_endpoint {
    function_id                       = "${azurerm_function_app.wvd["fa-azprd-frc-wvd-01"].id}/functions/Renew-RegistrationTokenAfterExpiration"
    max_events_per_batch              = 1
    preferred_batch_size_in_kilobytes = 64
  }

  #depends_on = [azurerm_function_app.wvd]
}